DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS PETS CASCADE;
DROP TABLE IF EXISTS REMINDERS CASCADE;
DROP TABLE IF EXISTS CONTACTS CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  names VARCHAR(255)[] NOT NULL,
);

CREATE TABLE pets
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  pet_img_url TEXT,
  date_of_birth DATE,
  species VARCHAR(255),
  weight VARCHAR(255)[],
  food VARCHAR(255),
  comment VARCHAR(500),
);

CREATE TABLE reminders
(
  id SERIAL PRIMARY KEY NOT NULL,
  pet_id INTEGER REFERENCES pets(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  date DATETIME NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  comment VARCHAR(500),
);

CREATE TABLE contacts
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  website VARCHAR(500),
);