DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS reminders CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  names VARCHAR(255)[] NOT NULL
);

CREATE TABLE pets
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  pet_img_url TEXT,
  date_of_birth DATE,
  variant VARCHAR(255),
  weight VARCHAR(255)[],
  food VARCHAR(255),
  comment VARCHAR(500)
);

CREATE TABLE reminders
(
  id SERIAL PRIMARY KEY NOT NULL,
  pet_id INTEGER REFERENCES pets(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  comment VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contacts
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  website VARCHAR(500)
);